### ISSUE TITLE
Styling blips with v0.2.1

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/sb#33]
SB v0.2.1 is functionally working fine. There are a couple of styling issues on my iPhone 13 mini and iPad.

- metadates wrapping
- no margins
- drop down menu styling for Sulphurous Brewmasters and Some Background
- font for tables could be smaller and/or horizontal scrolling supported
- Site Building menu minimises to hamburger

**Comment by bobbingwide** [comment]
> drop down menu styling for Sulphurous Brewmasters and Some Background

This should be fixed in v0.3.0

**Comment by bobbingwide** [comment]
> Site Building menu minimises to hamburger

The navigation block needs to have the `overlayMenu` attribute set to `never`.
``` 
<!-- wp:navigation {"overlayMenu":"never","layout":{"type":"flex","orientation":"vertical"}} -->
```

**Comment by bobbingwide** [comment]
> No margins

Can be resolved with some CSS for narrow devices
```
@media screen and  (max-width: 782px ) {
    .wp-site-blocks {
        margin: 0px 2%;
    }
}
```

**Comment by bobbingwide** [comment]
> metadates wrapping
![image](https://user-images.githubusercontent.com/2474435/183364971-6e556734-abf5-4b6c-893a-149e76e465a2.png)

It looks better when arranged as a stack consisting of rows.
![image](https://user-images.githubusercontent.com/2474435/183367834-b3a69ae7-452d-48c8-aaea-1577e384e197.png)

**Comment by bobbingwide** [comment]
> font for tables could be smaller and/or horizontal scrolling supported

On the **Table of attachments by date** page the `[bw_table]` shortcode is wrapped in a Group. 
Horizontal scrolling can be supported using inline CSS against this group.
```
 .wp-block-group {
overflow-x: auto;
overflow-y: hidden;
margin: 1em 0px;
}
```
Additional CSS styles the table.
```
table.bw_table { min-width: 800px; font-size: 14px; }
table th { text-align: left; }
```
- The table's minimum width is set to to the minimum width of the main content. 
- The font size is reduced to 14px
- The table headings are left aligned.

**Comment by bobbingwide** [comment]
- [x] metadates wrapping - see https://github.com/bobbingwide/sb/issues/33#issuecomment-1207799502
- [x] no margins - see https://github.com/bobbingwide/sb/issues/33#issuecomment-1207490015
- [x] drop down menu styling for Sulphurous Brewmasters and Some Background - see https://github.com/bobbingwide/sb/issues/33#issuecomment-1207481313
- [x] font for tables could be smaller and/or horizontal scrolling supported - see https://github.com/bobbingwide/sb/issues/33#issuecomment-1207809654
- [x]  Site Building menu minimises to hamburger - https://github.com/bobbingwide/sb/issues/33#issuecomment-1207489328

**Comment by bobbingwide** [comment]
These 5 blips have been fixed in v0.3.1
